### PR TITLE
Update bio + abstract Tim van Mourik

### PR DESCRIPTION
**Pull request by TimVanMourik**
I updated my info. I didn't test it out so I hope I didn't screw up any <> html tags.

### CODE REVIEW

**Comment by sofievdbos** [comment]
Thank you; as some other code lines were already changed, I implemented your bio and abstract in the updated files. If you want to change something, feel free to add another PR! :)

**Comment by TimVanMourik** [comment]
@sofievdbos I just the title in the programme hasn't been updated. Would you mind resolving that? Thanks!

**Comment by sofievdbos** [comment]
@TimVanMourik Could you specify the title once more? At the moment, the title is 'Open Source Neuroimaging Pipelines with GiraffeTools' in both the Program and in the abstract (Speakers page).

**Comment by TimVanMourik** [comment]
The title is: "<title>Web technologies in neuroimaging</title>"
preferably including the 'title' tags.

See below for the abstract
```
<div class="popup" onclick="myFunction_tim()"><p>
<strong>Web technologies in neuroimaging</strong>
</p>
  <span class="popuptext" id="myPopup_tony"><b>Abstract: </b>
    How do we share and communicate your analysis pathways? By means of a text-description in a paper, or are there other ways? In this day and age where everything happens online, it should be possible to leverage web technologies for neuroimaging. Indeed, there is a growing number of web tools to share and communicate project information, data sets, and entire interactive workflows online. In this talk I will discuss a variety of these projects, how to get started or even involved in them, and what I believe is the future of data analysis and neuroimaging.
  </span>
</div>
```

**Comment by sofievdbos** [comment]
@TimVanMourik I adapted the title in both the Program and in the abstract (Speakers page). However, I was not able to use the 'title' tags. :(  When using those, the title was invisible on the website. At the moment, I don't know why... Do you have an idea?

**Comment by TimVanMourik** [comment]
Haha, my hunch is that the title tags are indeed interpreted as a <title> element in html, that sets the tab content of the page. The trick is to 'escape' the < and the > to make sure that they're not interpreted as html block. In all likelihood, if you replace the < by `&lt;` and > by `&lt;` it works fine :) 

*check out https://en.wikipedia.org/wiki/Character_encodings_in_HTML if you're interested.

**Pull request closed without merging**
