### PR TITLE
Sprint to the finish

### PR DESCRIPTION
**Pull request by sofievdbos**

### CODE REVIEW

**Review by Remi-Gau — APPROVED** [review]
LGTM

**Review by DorienHuijser — APPROVED** [review]

**Comment by DorienHuijser** [comment]
Looks great! Can we make the sign-up sheet for people who want to be in next year's committee more prominent maybe? Ideas?

**Comment by sofievdbos** [comment]
Embed on home page instead of just a link?

**Comment by DorienHuijser** [comment]
> Embed on home page instead of just a link?

Sure!

Stephan is not visible on the speakers page day 2! Need to fix that before merging :D

**Comment by DorienHuijser** [comment]
Approved once more :D

**Comment by sofievdbos** [comment]
Embedded!

**Comment by sofievdbos** [comment]
@jsheunis Any comments (CoC note on home page = okay)?

**Comment by jsheunis** [comment]
1. The grey section that contains comments about CoC etc seems to interfere with the twitter component. I think we should update the margins on the grey component such that it agrees with the sections above it. The content in the grey section is great 👍 
2. The google form on the home page doesn't render for me, but that's also been an issue for me with the registration form. So it's probably a browser issue.
3. Everything else looks great, thanks so much!

**Comment by sofievdbos** [comment]
1. That's a Markdown `<blockquote>` command. Not sure how to update the margins on that one (or whether it's even possible using `<blockquote>`)? 
2. Hmmmm, it's rendering for me. Which browser are you using?

**Comment by jsheunis** [comment]
1. Is this issue visible for anyone else?
2. Chrome

**Comment by sofievdbos** [comment]
1. I do see it, but I didn't think it was very bothersome:<br>
image<br><br>
2. Me too ...

**Comment by jsheunis** [comment]
I'll go ahead and merge it anyways... :)

**Review by jsheunis — APPROVED** [review]

**Pull request merged**
