### PR TITLE
2021 framework

### PR DESCRIPTION
**Pull request by DorienHuijser**
Update website

### CODE REVIEW

**Review by Remi-Gau — CHANGES_REQUESTED** [review]
Hey @DorienHuijser 

I just checked. Thanks for taking care of this.

One thing that would be nice is to make sure the images of team (and speakers) are cropped to be square images otherwise we get some weird things (oval and not circles) when displaying them.

There is a way around this but it might require a bit more work on the CSS end I think.
https://www.sitepoint.com/community/t/keep-image-aspect-ratio/34593/8

Another "detail" that can be nice in the long run making sure the images are not "too" big in size which helps loading time (and also makes it lighter to push and pull stuff from the repo).

In general we don't need pics that are more than 500 ko.

I just checked and we have some LARGE picture in there.

I can edit them or let you do it, what do you prefer?

**Comment by DorienHuijser** [comment]
Thanks @Remi-Gau! I can def make some pictures smaller in size, but the css-thing is a bit advanced for me I think 😆 Can you take care of that maybe?

**Comment by Remi-Gau** [comment]
I don't have the time right now so let's go with making sure that the pictures are cropped to have the same height and width.

I will open an issue to make sure we remember to improve that in the future. :-)

**Comment by DorienHuijser** [comment]
@Remi-Gau I made the img squared by hand and the larger ones smaller in file size. Merge now?

**Review by Remi-Gau — APPROVED** [review]
Go ahead ! Merge this big baby ! :baby:

**Pull request merged**
