### PR TITLE
2021 framework

### PR DESCRIPTION
**Pull request by DorienHuijser**
Update the website, merge 2021-framework branch

### CODE REVIEW

**Comment by DorienHuijser** [comment]
@Remi-Gau we blocked merging PRs ourselves so I assigned you to review, so sorry if this is too much work for you..

**Comment by Remi-Gau** [comment]
@DorienHuijser I will serve the website locally and make sure it looks OK.
Don't really have time to check all the code change. :stuck_out_tongue_closed_eyes:

**Comment by DorienHuijser** [comment]
@Remi-Gau No problem of course!! I also already checked it out before merging dorienhuijser/2021-framework with openmrb/2021-framework, so I think all should be ok :)

**Review by Remi-Gau — APPROVED** [review]
good to go

**Pull request merged**
