### PR TITLE
fix speakers column

### LINKED ISSUE #63: Edit speakers.html to not hard-code nr of columns
Patricia Clement's tile is now not visible because the nr of columns is hard-coded to 6 in `speakers.html`. If I change it to 7 or 8, the tiles in the right column just become larger (problem may be an uneven nr of tiles). Needs to be fixed but I'm not sure how!

**code in `speakers.html`**
`{% if day.date == "Day 3: Friday, 26 March 2021" %}{% assign lim = '6' %}{% endif %}`
and
`{% if loop == 1 and day.date == "Day 3: Friday, 26 March 2021" %}{% assign nr = '6' %}{% endif %}`
and
`{% for speaker in day.speakers limit: lim offset: nr %}`

### PR DESCRIPTION
**Pull request by Remi-Gau**
should fix  #63

### CODE REVIEW

**Comment by DorienHuijser** [comment]
I tried changing it to 7, but now Stijn is shown twice!

**Comment by DorienHuijser** [comment]
We could leave it like that, not sure anyone would notice it haha

**Comment by sofievdbos** [comment]
I did a PR on the `Remi-Gau:temp` branch.

**Review by sofievdbos — APPROVED** [review]
All good! 😁

**Pull request merged**
